test2

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -1,17 +1,22 @@
-on: push
-name: deploy
+name: Push docker image
+on:
+  workflow_dispatch:
+    inputs:
+      buildEnv:
+        description: 'Build Environment (dev or prod)'
+        required: true
+        default: 'dev'
 jobs:
-  deploy:
-    name: deploy to cluster
-    runs-on: ubuntu-latest
+  build-image:
+    runs-on: beracahmx/odoo:dev-testbuild
     steps:
-      - uses: actions/checkout@master
-      - name: build and push to docker
-        uses: docker/build-push-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-          repository: ${{ github.repository }}
-          tag_with_ref: true
-          tag_with_sha: true
-          tags: ${{ github.sha }}
+      - uses: actions/checkout@v2
+      - name: Push image to docker hub
+        env:
+          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
+          DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
+        run: |
+          IMAGE_TAG=${{ steps.dockerbuild.outputs.image-tag }}
+          echo "[INFO]: upload image to DockerHub"
+          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD || { echo "Error en docker login"; exit 1; }
+          docker push beracahmx/web:$IMAGE_TAG || { echo "Error en docker push"; exit 1; }
